version: '3'

services:
  app:
    image: vk-dynamic-profile-status
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vk-dynamic-prifile-status

    environment:
      - TOKEN=your_token
      - TZ=Europe/Moscow # your time zone
      - CITY=your_city # city for forecast in profile status
      - ACCUWEATHER_API_KEY=your_token
      - STATUS_FORMAT={time} {emoji} | {forecast}
    restart: always