version: '3'

services:
  app:
    image: vk-dynamic-profile-status
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vk-dynamic-prifile-status

    environment:
      - TOKEN= #your token
      - TZ=Europe/Moscow # your time zone
      - CITY= # city for forecast in profile status
      - ACCUWEATHER_API_KEY= # your token
      - STATUS_FORMAT={time} {emoji} | {forecast} # your format
    restart: always